server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/skku?&characterEncoding=UTF-8
    username: skku-user
    password: skku-pw
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        check_nullability: true
        use_sql_comments: true
        format_sql: false
        show_sql: false
  redis:
    host: skku-redis
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

es:
  host: es-singlenode
  port: 9200

aws:
  s3:
    region: ${AWS_S3_REGION:test}
    bucket: ${AWS_COMPRESSED_BUCKET:test}
  access-s3-key: ${AWS_ACCESS_S3_KEY:test}
  secret-s3-key: ${AWS_SECRET_S3_KEY:test}
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_SECRET_KEY:test}
  sender-email: ${SENDER_EMAIL:test}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false

