server:
  port: 8080

spring:
  application:
    name: be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/skku?&characterEncoding=UTF-8
    username: skku-user
    password: skku-pw
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        check_nullability: true
        use_sql_comments: true
        format_sql: false
        show_sql: false
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  access-token-validity-in-seconds: 32140800
  refresh-token-validity-in-seconds: 1209600

aws:
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_SECRET_KEY:test}
  sender-email: ${SENDER_EMAIL:tlsrudejr123@g.skku.edu}

es:
  host: localhost
  port: 9200

discord:
  monitor: ${DISCORD_MONITOR:https:test}

aligo:
  key: ${ALIGO_API_KEY:zg2xg4apjbunl3okizg4zcdrlfryjs5q}
  user-id: ${ALIGO_USER_ID:ting70ok}
  sender: ${ALIGO_SENDER_PHONE:01041805905}
  test-mode: ${ALIGO_TEST_MODE:Y}

kakao:
  key: ${KAKAO_API_KEY:testKey}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/kakao/test}


logging:
  level:
    root: info
