
### 리뷰 생성
POST {{host}}/v1/restaurants/1/reviews
Content-Type: application/json
Authorization: {{auth_token}}

{
  "rating": 0,
  "content": "",
  "imageUrls": []
}

### 리뷰 삭제
DELETE {{host}}/v1/restaurants/reviews/1
Content-Type: application/json
Authorization: {{auth_token}}

{
  "rating": 0,
  "content": "",
  "imageUrls": []
}

### 내 리뷰 조회
GET {{host}}/v1/restaurants/my-reviews
Content-Type: application/json
Authorization: {{auth_token}}

### 식당의 모든 리뷰 조회
GET {{host}}/v1/restaurants/1/reviews
Content-Type: application/json
Authorization: {{auth_token}}

{
  "rating": 0,
  "content": "",
  "imageUrls": []
}

### 리뷰 단건 조회
GET {{host}}/v1/restaurants/reviews/1
Content-Type: application/json
Authorization: {{auth_token}}

{

}

### 리뷰 변경
PATCH {{host}}/v1/restaurants/reviews/1/reviews/1
Content-Type: application/json
Authorization: {{auth_token}}

{
  "review": {}
}

### 리뷰 좋아요
POST {{host}}/v1/restaurants/reviews/1/like
Content-Type: application/json
Authorization: {{auth_token}}

{
  "isLike": true
}
