### ⚡ 비동기 업로드 테스트 (코루틴)
POST {{host}}/v1/upload-image/async
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{auth_token}}

--boundary
Content-Disposition: form-data; name="path"

REVIEW
--boundary
Content-Disposition: form-data; name="files"; filename="image1.jpg"
Content-Type: image/jpeg

< ./test-images/image1.jpg
--boundary
Content-Disposition: form-data; name="files"; filename="image2.jpg"
Content-Type: image/jpeg

< ./test-images/image1.jpg
--boundary
Content-Disposition: form-data; name="files"; filename="image3.jpg"
Content-Type: image/jpeg

< ./test-images/image1.jpg
--boundary--